title = "StillMe Gitleaks Rules"

[allowlist]
paths = [
  '''^build/''',
  '''^\.dart_tool/''',
  '''^\.gradle/''',
  '''^android/app/build/''',
  '''^ios/Pods/''',
]

regexes = [
  '''FAKE|DUMMY|PLACEHOLDER|EXAMPLE_KEY'''
]
 security/remove-sensitive-files

 fix/gitleaks-workflow


 main
 main
