[server]
headless = true
port = 8080
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
runOnSave = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false
serverAddress = ""

[theme]
primaryColor = "#46b3ff"
base = "dark"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#ffffff"
font = "sans serif"

